
# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  # Thay đổi nếu bạn sử dụng branch khác
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.13'  # Thay đổi phiên bản Python nếu cần

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           python manage.py test

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main'  # Chỉ triển khai khi có đẩy lên nhánh main

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up SSH
#         run: |
#           # Start the SSH agent
#           eval "$(ssh-agent -s)"
          
#           # Add private key from GitHub Secrets to the SSH agent
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          
#           # Create SSH directory and set proper permissions
#           mkdir -p ~/.ssh
#           chmod 700 ~/.ssh
          
#           # Add the server's public key to the known_hosts file to avoid SSH verification issues
#           touch ~/.ssh/known_hosts
#           ssh-keyscan -H 159.223.113.204 >> ~/.ssh/known_hosts
#           chmod 644 ~/.ssh/known_hosts


#       - name: Deploy to DigitalOcean
#         run: |
#           cd root/test/deploy_django
#           git pull origin main
#           source venv/bin/activate
#           pip install -r requirements.txt
#           python manage.py migrate
#           sudo systemctl restart gunicorn  # Restart Gunicorn service
#           sudo systemctl restart nginx  # Restart Nginx service


name: Deploy Django to DigitalOcean

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn deploy từ đó

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/deploy_django
          git pull origin main
          source venv/bin/activate  # Nếu sử dụng virtualenv
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart gunicorn
          systemctl restart nginx
